image: python:latest

pages:
  script:
  - pip install -U sphinx sphinx_book_theme myst_parser sphinxcontrib.jquery sp$ry sphinx_copybutton sphinx_design sphinx_togglebutton make
  - make html
  - cp -r source/nccoe-bank public/
  artifacts:
    paths:
    - public
