stages:
  - build-sphinx
  - build-vue
  - deploy

build_sphinx_app:
  image: python:latest
  stage: build-sphinx
  script:
    - pip install -r requirements.txt
    - make html BUILDDIR=public/nccoe-mdl-project-static-website
  artifacts:
    paths:
      - public/nccoe-mdl-project-static-website/
    expire_in: 1 hour

build_vue_app:
  image: node:latest
  stage: build-vue
  script:
    - cd source/nccoe-bank
    - npm install
    - npm run build
    - mkdir -p ../../public/nccoe-mdl-project-static-website/nccoe-bank
    - cp -r dist/* ../../public/nccoe-mdl-project-static-website/nccoe-bank/
  artifacts:
    paths:
      - public/nccoe-mdl-project-static-website/nccoe-bank/
    expire_in: 1 hour

pages:
  image: busybox:latest
  stage: deploy
  script:
    - echo "Deploying GitLab Pages..."
  artifacts:
    paths:
      - public
