name: Comment
description: Submit a comment
body:
  - type: input
    id: org
    attributes:
      label: Organization
      description: "The name of the organization you represent."
    validations:
      required: false
  - type: input
    id: requirement
    attributes:
      label: Requirement ID
      description: "The ID number of the requirement you are commenting on. If your comment is not specific to a requirement, please identify the specific section of the site that you are addressing instead."
    validations:
      required: false
  - type: textarea
    id: comment
    attributes:
      label: Comment
    validations:
      required: true
